/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ctmarks;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Ashish
 */
public class AddCT extends javax.swing.JFrame {

    /**
     * Creates new form AddCT
     */
    public AddCT() {
        initComponents();
        jLabel3.setFocusable(true);
        s6.setVisible(false);
        m6.setVisible(false);
        jSeparator8.setVisible(false);
        jSeparator14.setVisible(false);
        //this.setSize(800,500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        t1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        t2 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        t3 = new javax.swing.JComboBox<>();
        t4 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        s1 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        s2 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        s3 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        s4 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        s5 = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        s6 = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        m1 = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        m2 = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        m3 = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        m4 = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        m5 = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        m6 = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        co1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel1.setBackground(new java.awt.Color(43, 42, 76));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t1.setBackground(new java.awt.Color(43, 42, 76));
        t1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        t1.setForeground(new java.awt.Color(255, 255, 255));
        t1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t1.setText("Roll No.");
        t1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        t1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        t1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t1FocusLost(evt);
            }
        });
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        jPanel1.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 210, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 210, 10));

        jButton1.setBackground(new java.awt.Color(43, 42, 76));
        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Go");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 60, 40));

        t2.setBackground(new java.awt.Color(43, 42, 76));
        t2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        t2.setForeground(new java.awt.Color(255, 255, 255));
        t2.setText("Name");
        t2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        t2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t2FocusLost(evt);
            }
        });
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        jPanel1.add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 460, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 460, 20));

        t3.setBackground(new java.awt.Color(43, 42, 76));
        t3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        t3.setForeground(new java.awt.Color(255, 255, 255));
        t3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "                --Branch--", "Aeronautical Engineering", "Aerospace Engineering", "Aircraft Maintenance Engineering ", "Automobile Engineering", "Biotechnology Engineering", "Chemical Engineering", "Civil Engineering", "Computer Science Engineeering", "Electrical Engineering", "Electrical & Electronics Engineering", "Electrical & Telecommunications Engineering", "Information Technology Engineering", "Mechanical Engineering", "Metallurgical Engineering" }));
        t3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(42, 43, 76)));
        jPanel1.add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 270, 40));

        t4.setBackground(new java.awt.Color(43, 42, 76));
        t4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        t4.setForeground(new java.awt.Color(255, 255, 255));
        t4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "    --Semester--", "1", "2", "3", "4", "5", "6", "7", "8" }));
        jPanel1.add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 170, 40));

        jButton2.setBackground(new java.awt.Color(43, 42, 76));
        jButton2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Add Subjects");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 150, 40));

        jButton3.setBackground(new java.awt.Color(43, 42, 76));
        jButton3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Get Subjects");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 150, 40));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 3, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Marks");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 90, 30));

        s1.setBackground(new java.awt.Color(43, 42, 76));
        s1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        s1.setForeground(new java.awt.Color(255, 255, 255));
        s1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        s1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                s1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                s1FocusLost(evt);
            }
        });
        s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1ActionPerformed(evt);
            }
        });
        jPanel1.add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 270, 30));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 270, 20));

        s2.setBackground(new java.awt.Color(43, 42, 76));
        s2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        s2.setForeground(new java.awt.Color(255, 255, 255));
        s2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        s2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                s2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                s2FocusLost(evt);
            }
        });
        s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s2ActionPerformed(evt);
            }
        });
        jPanel1.add(s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 270, 30));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 270, 20));

        s3.setBackground(new java.awt.Color(43, 42, 76));
        s3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        s3.setForeground(new java.awt.Color(255, 255, 255));
        s3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        s3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                s3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                s3FocusLost(evt);
            }
        });
        s3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s3ActionPerformed(evt);
            }
        });
        jPanel1.add(s3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 270, 30));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 270, 20));

        s4.setBackground(new java.awt.Color(43, 42, 76));
        s4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        s4.setForeground(new java.awt.Color(255, 255, 255));
        s4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        s4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                s4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                s4FocusLost(evt);
            }
        });
        s4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s4ActionPerformed(evt);
            }
        });
        jPanel1.add(s4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 270, 30));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 270, 20));

        s5.setBackground(new java.awt.Color(43, 42, 76));
        s5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        s5.setForeground(new java.awt.Color(255, 255, 255));
        s5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        s5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                s5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                s5FocusLost(evt);
            }
        });
        s5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s5ActionPerformed(evt);
            }
        });
        jPanel1.add(s5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 270, 30));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 270, 20));

        s6.setBackground(new java.awt.Color(43, 42, 76));
        s6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        s6.setForeground(new java.awt.Color(255, 255, 255));
        s6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        s6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                s6FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                s6FocusLost(evt);
            }
        });
        s6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s6ActionPerformed(evt);
            }
        });
        jPanel1.add(s6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 270, 30));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 270, 20));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 3, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Subjects");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 90, 30));

        m1.setBackground(new java.awt.Color(43, 42, 76));
        m1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        m1.setForeground(new java.awt.Color(255, 255, 255));
        m1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        m1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                m1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                m1FocusLost(evt);
            }
        });
        m1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m1ActionPerformed(evt);
            }
        });
        jPanel1.add(m1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 170, 30));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 170, 20));

        m2.setBackground(new java.awt.Color(43, 42, 76));
        m2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        m2.setForeground(new java.awt.Color(255, 255, 255));
        m2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        m2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                m2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                m2FocusLost(evt);
            }
        });
        m2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m2ActionPerformed(evt);
            }
        });
        jPanel1.add(m2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 170, 30));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 170, 20));

        m3.setBackground(new java.awt.Color(43, 42, 76));
        m3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        m3.setForeground(new java.awt.Color(255, 255, 255));
        m3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        m3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                m3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                m3FocusLost(evt);
            }
        });
        m3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m3ActionPerformed(evt);
            }
        });
        jPanel1.add(m3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 170, 30));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 170, 20));

        m4.setBackground(new java.awt.Color(43, 42, 76));
        m4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        m4.setForeground(new java.awt.Color(255, 255, 255));
        m4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        m4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                m4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                m4FocusLost(evt);
            }
        });
        m4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m4ActionPerformed(evt);
            }
        });
        jPanel1.add(m4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 170, 30));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 170, 20));

        m5.setBackground(new java.awt.Color(43, 42, 76));
        m5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        m5.setForeground(new java.awt.Color(255, 255, 255));
        m5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        m5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                m5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                m5FocusLost(evt);
            }
        });
        m5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m5ActionPerformed(evt);
            }
        });
        jPanel1.add(m5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 170, 30));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 170, 20));

        m6.setBackground(new java.awt.Color(43, 42, 76));
        m6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        m6.setForeground(new java.awt.Color(255, 255, 255));
        m6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        m6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                m6FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                m6FocusLost(evt);
            }
        });
        m6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m6ActionPerformed(evt);
            }
        });
        jPanel1.add(m6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 170, 30));
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, 170, 20));

        jButton4.setBackground(new java.awt.Color(43, 42, 76));
        jButton4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Save");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 110, 40));

        jButton5.setBackground(new java.awt.Color(43, 42, 76));
        jButton5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 410, 110, 40));

        co1.setBackground(new java.awt.Color(43, 42, 76));
        co1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        co1.setForeground(new java.awt.Color(255, 255, 255));
        co1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "           --CT--", "1", "2" }));
        jPanel1.add(co1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, 170, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ashish\\Downloads\\learning3.png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t1FocusGained
        // TODO add your handling code here:
        if(t1.getText().equals("Roll No."))
        {
            t1.setText("");
        }
    }//GEN-LAST:event_t1FocusGained

    private void t1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t1FocusLost
        // TODO add your handling code here:
        if(t1.getText().equals(""))
        {
            t1.setText("Roll No.");
        }
    }//GEN-LAST:event_t1FocusLost

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void t2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t2FocusGained
        // TODO add your handling code here:
        if(t2.getText().equals("Name"))
        {
            t2.setText("");
        }
    }//GEN-LAST:event_t2FocusGained

    private void t2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t2FocusLost
        // TODO add your handling code here:
        if(t2.getText().equals(""))
        {
            t2.setText("Name");
        }
    }//GEN-LAST:event_t2FocusLost

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
            String r=t1.getText();   
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/ctproject","root","");
            String q="select * from student where roll_no='"+r+"'";
           Statement stmt=con.createStatement();
           ResultSet rs=stmt.executeQuery(q);
           while(rs.next())
           {
               t2.setText(rs.getString("name"));
               t3.setSelectedItem(rs.getString("branch"));
               t4.setSelectedItem(rs.getString("sem"));
           }   
           con.close();
        }
        catch(Exception ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        s6.setVisible(true);
        m6.setVisible(true);
        jSeparator8.setVisible(true);
        jSeparator14.setVisible(true);
        pack();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String b=(String) t3.getSelectedItem();
        String s=(String) t4.getSelectedItem();
    if(b.equals("Aeronautical Engineering"))
    {
        if(s.equals("1"))
        {
            s1.setText("Technical English-I");
            s2.setText("Engineering Physics-I");
            s3.setText("Mathematics-I");
            s4.setText("Engineering Chemistry-I");
            s5.setText("Computer Programming");
            s6.setText("Engineering Graphics");
        }
        if(s.equals("2"))
        {
            s1.setText("Technical English-II");
            s2.setText("Engineering Physics-II");
            s3.setText("Mathematics-II");
            s4.setText("Engineering Chemistry-II");
            s5.setText("Basic Electrical & Electronics Engineering");
            s6.setText("Engineering Mechanics");
        }
        if(s.equals("3"))
        {
            s1.setText("Transforms & Partial Differential Equations");
            s2.setText("Manufacturing Technology");
            s3.setText("Aero Engineering Dynamics");
            s4.setText("Fluid Mechanics & Machinery");
            s5.setText("Solid Mechanics");
            s6.setText("Elements Of Aeronautics");
        }
        if(s.equals("4"))
        {
            s1.setText("Numerical Methods");
            s2.setText("Aerodynamics-I");
            s3.setText("Aircraft Systems & Instruments");
            s4.setText("Mechanics Of Machines");
            s5.setText("Aircraft Structures-I");
            s6.setText("Propulsion-I");
        }
        if(s.equals("5"))
        {
            s1.setText("Flight Dynamics");
            s2.setText("Aircraft Structures-II");
            s3.setText("Aerodynamics-II");
            s4.setText("Propulsion-II");
            s5.setText("Control Engineering");
            s6.setText("Environmental Science & Engineering");
        }
        if(s.equals("6"))
        {
            s1.setText("Principles Of Management");
            s2.setText("Finite Element Methods");
            s3.setText("Vibrations & Elements Of Aeroelasticity");
            s4.setText("Composite Materials & Strutures");
            s5.setText("Aircraft Materials & Processes");
            s6.setText("Space Mechanics");
        }
        if(s.equals("7"))
        {
            s1.setText("Total Quality Management");
            s2.setText("Avionics");
            s3.setText("Computational Fluid Dynamics");
            s4.setText("Experimental Stress Analysis");
            s5.setText("Helicopter Theory");
            s6.setText("UAV Systems");
        }
        if(s.equals("8"))
        {
            s1.setText("Wind Tunnel Techniques");
            s2.setText("Hypersonic Aerodynamics");
            s3.setText("Experimental Aerodynamics");
            s4.setText("Rockets & Missiles");
            s5.setText("Structural Dynamics");
        }
    }
    if(b.equals("Aerospace Engineering"))
    {
        if(s.equals("1"))
        {
            s1.setText("Calculus");
            s2.setText("Physics-I");
            s3.setText("Chemistry");
            s4.setText("Introduction to Aerospace Engineering ");
            s5.setText("Basic Electrical Engineering");
            s6.setText("Communication Skills");
        }
        if(s.equals("2"))
        {
            s1.setText("Vector Calculus & Ordinary Differential Equations");
            s2.setText("Physics-II");
            s3.setText("Material Science & Metallurgy");
            s4.setText("Basic Electronics Engineering");
            s5.setText("Engineering Graphics");
            s6.setText("Computer Programming & Applications");
        }
        if(s.equals("3"))
        {
            s1.setText("Linear Algebra, Complex Analysis & Fourier Series");
            s2.setText("Engineering Therodynamics");
            s3.setText("Mechanics Of Solids");
            s4.setText("Fluid Mechanics");
            s5.setText("Manufacturing Technology");
            s6.setText("Introduction to Machine Elements & Drawing");
        }
        if(s.equals("4"))
        {
            s1.setText("Integral Transforms,PDE & Calculus Of Variations");
            s2.setText("Aerodynamics");
            s3.setText("Heat Transfer");
            s4.setText("Applied Dynamics & Variations");
            s5.setText("Machining & Precision Manufacturing");
            s6.setText("Metrology & Computer Aided Inspection");
        }
        if(s.equals("5"))
        {
            s1.setText("Probability, Statistics & Numerical Methods");
            s2.setText("Compressible Flow");
            s3.setText("Atmospheric Flight Mechanics");
            s4.setText("Spaceflight Mechanics");
            s5.setText("Automatic Control");
            s6.setText("Theory Of Elasticity");
        }
        if(s.equals("6"))
        {
            s1.setText("Air-Breathing Propulsion");
            s2.setText("Aerospace Structures");
            s3.setText("Optimization Techniques in Engineering");
            s4.setText("Principles Of Management Systems");
            s5.setText("Aerospace Materials & Processes");
            s6.setText("Aeroacoustics");
        }
        if(s.equals("7"))
        {
            s1.setText("Rocket Propulsion");
            s2.setText("Aerospace Vehicle Design");
            s3.setText("Environmental Science & Engineering");
            s4.setText("Space Mission Design & Optimization");
            s5.setText("Refrigeration & Cryogenics");
        }
        if(s.equals("8"))
        {
            s1.setVisible(false);
             s2.setVisible(false);
              s3.setVisible(false);
             s4.setVisible(false);
             s5.setVisible(false);
             m1.setVisible(false);
            m2.setVisible(false);
             m3.setVisible(false);
              m4.setVisible(false);
            m5.setVisible(false);
            JOptionPane.showMessageDialog(this, "No Class-Test in this Semester !");
        }
    }
    if(b.equals("Computer Science Engineering"))
    {
        if(s.equals("1"))
        {
            s1.setText("Applied Physics");
            s2.setText("Fundamentals Of Mechanical Engineering");
            s3.setText("Mathematics-I");
            s4.setText("Environment & Ecology");
            s5.setText("Basic Civil Engineering");
        }
        if(s.equals("2"))
        {
            s1.setText("Applied Chemistry");
            s2.setText("Elements Of Electrical Engineering");
            s3.setText("Mathematics-II");
            s4.setText("Communication Skills");
            s5.setText("Engineering Graphics");
        }
        if(s.equals("3"))
        {
            s1.setText("Mathematics-III");
            s2.setText("Problem Solving & Logic Building using C");
            s3.setText("Computational Science");
            s4.setText("Computer Concepts & Web Technology");
            s5.setText("Digital Electronics & Logic Building");
            s6.setText("Basic Electronics");
        }
        if(s.equals("4"))
        {
            s1.setText("Object Oriented Programming & Concepts with C++");
            s2.setText("Data Structures");
            s3.setText("Computational Mathematics");
            s4.setText("Discrete Structures");
            s5.setText("Computer System & Architecture ");
            s6.setText("Operating System");
        }
        if(s.equals("5"))
        {
            s1.setText("Microprocessor & Interfaces");
            s2.setText("Analytics & Designs Algorithms");
            s3.setText("Programming in Java");
            s4.setText("Theory Of Computation");
            s5.setText("Unix & Shell Programming");
            s6.setText("Database Management System");
        }
        if(s.equals("6"))
        {
            s1.setText("Computer Networks");
            s2.setText("Compiler Design");
            s3.setText("Enterprise Resource Planning");
            s4.setText("Software Engineering & Project Management");
            s5.setText("Computer Graphics");
            s6.setText("Inter-Networking with TCP/IP");
        }
        if(s.equals("7"))
        {
            s1.setText("Mobile Computing & Application");
            s2.setText("Parallel Processing & Computing");
            s3.setText("Network Programming");
            s4.setText("Cryptography & Network Security");
            s5.setText("Cloud Computing");
        }
        if(s.equals("8"))
        {
            s1.setText("Artificial Intelligence & Expert Systems");
            s2.setText("Data Mining & Ware Housing");
            s3.setText("Cyber Security");
            s4.setText("Wireless Networks");
            s5.setText("Software Technology");
        }
    }
    if(b.equals("Information Technology Engineering"))
    {
        if(s.equals("1"))
        {
            s1.setText("Applied Chemistry");
            s2.setText("Elements  Of Electrical Engineering");
            s3.setText("Mathematics-I");
            s4.setText("Communication Skills");
            s5.setText("Engineering Graphics");
        }
        if(s.equals("2"))
        {
            s1.setText("Applied Physics");
            s2.setText("Fundamentals Of Mechanical Engineering");
            s3.setText("Mathematics-II");
            s4.setText("Environment & Ecology");
            s5.setText("Basic Civil Engineering");
        }
        if(s.equals("3"))
        {
            s1.setText("Discrete Structures");
            s2.setText("Mathematics-III");
            s3.setText("Basic Electronics & Network Theory");
            s4.setText("Concepts Of IT & Web Technology");
            s5.setText("Problem Solving & LOgic Building using C");
            s6.setText("Digital Electronics & Logic Building");
        }
        if(s.equals("4"))
        {
            s1.setText("Computational Mathematics");
            s2.setText("Telecom Switching & Computer Networks");
            s3.setText("Analog Electronics & Circuits");
            s4.setText("Object Oriented Concepts & Programming using C++");
            s5.setText("Computer Organization & Architecture");
            s6.setText("Data Structures & Algorithm Analysis");
        }
        if(s.equals("5"))
        {
            s1.setText("Microprocessor & Interfaces");
            s2.setText("Principles Of Commuication System");
            s3.setText("Database Management System");
            s4.setText("Operating System");
            s5.setText("Programming in Java");
            s6.setText("Theory Of Computation");
        }
        if(s.equals("6"))
        {
            s1.setText("Web Application Development");
            s2.setText("Information Theory & Coding");
            s3.setText("Software Engineering & Project Management");
            s4.setText("UNIX & Shell Programming");
            s5.setText("Computer Graphics & Animation");
            s6.setText("Multimedia & Virtual Reality");
        }
        if(s.equals("7"))
        {
            s1.setText("Data Mining & Ware Housing");
            s2.setText("Management Information System & IT");
            s3.setText("Artificial Intelligence & Expert Systems");
            s4.setText("Cryptography & Network Security");
            s5.setText("Natural Languages Processing");
        }
        if(s.equals("8"))
        {
            s1.setText("Enterprise Resource Planning");
            s2.setText("Mobile Computing & Application");
            s3.setText("Cyber Security");
            s4.setText("Advanced Information System");
            s5.setText("Bio Informatics");
        }
    }
    if(b.equals("Automobile Engineering"))
    {
        if(s.equals("1"))
        {
            s1.setText("Applied Chemistry");
            s2.setText("Elements  Of Electrical Engineering");
            s3.setText("Mathematics-I");
            s4.setText("Communication Skills");
            s5.setText("Engineering Graphics");
        }
        if(s.equals("2"))
        {
            s1.setText("Applied Physics");
            s2.setText("Fundamentals Of Mechanical Engineering");
            s3.setText("Mathematics-II");
            s4.setText("Environment & Ecology");
            s5.setText("Basic Civil Engineering");
        }
        if(s.equals("3"))
        {
            s1.setText("Mathematics-III");
            s2.setText("Machine Drawing");
            s3.setText("Automotive Petrol Engines");
            s4.setText("Mechanics Of Solids");
            s5.setText("Engineering Thermodynamics");
            s6.setText("Two & Three Wheeler");
        }
        if(s.equals("4"))
        {
            s1.setText("Fluid Mechanics");
            s2.setText("Automotive Diesel Engines");
            s3.setText("Applied Thermodynamics");
            s4.setText("Kinematics Of Machines");
            s5.setText("Autoative Chasis");
            s6.setText("Manufacturing Science-I");
        }
        if(s.equals("5"))
        {
            s1.setText("Design Of Machine Elements");
            s2.setText("Automtive Transmission");
            s3.setText("Dynamics Of Machines");
            s4.setText("Automotive Electrical & Electronics");
            s5.setText("Automotive Fuels & Lubricants");
            s6.setText("Operation Research");
        }
        if(s.equals("6"))
        {
            s1.setText("Vehicle Maintenance");
            s2.setText("Vehicle Design");
            s3.setText("Automotive Engine Component Design");
            s4.setText("Heat & Mass Transfer");
            s5.setText("Production Management");
            s6.setText("Vehicle Transport Management");
        }
        if(s.equals("7"))
        {
            s1.setText("Automotive Air Coditioning");
            s2.setText("Vehicle Body Engineering & Safety");
            s3.setText("Computer Aided Design & Manufacturing");
            s4.setText("Vehicle Dynamics");
            s5.setText("Auto Pollution Control");
        }
        if(s.equals("8"))
        {
            s1.setText("Robotics");
            s2.setText("Manufacturing Technology");
            s3.setText("Industrial Engineering & Management");
            s4.setText("Fuel Cell Technology");
            s5.setText("Managing Innovation & Entrepreneurship");
        }
    }
    if(b.equals("Civil Engineering"))
    {
        if(s.equals("1"))
        {
            s1.setText("Applied Physics");
            s2.setText("Fundamentals Of Mechanical Engineering");
            s3.setText("Mathematics-I");
            s4.setText("Environment & Ecology");
            s5.setText("Basic Civil Engineering");
        }
        if(s.equals("2"))
        {
            s1.setText("Applied Chemistry");
            s2.setText("Elements Of Electrical Engineering");
            s3.setText("Mathematics-III");
            s4.setText("Communication Skills");
            s5.setText("Engineering Graphics");
        }
        if(s.equals("3"))
        {
            s1.setText("Mathematics-III");
            s2.setText("Fluid Mechanics-I");
            s3.setText("Surveying-I");
            s4.setText("Mechanics Of Solids");
            s5.setText("Building Materials");
            s6.setText("Engineering Geology");
        }
        if(s.equals("4"))
        {
            s1.setText("Structural Analysis-I");
            s2.setText("Fluid Mechanics-II");
            s3.setText("Surveyingi-II");
            s4.setText("Civil Engineering Drawing");
            s5.setText("Building Construction");
            s6.setText("Transportation Engineering-I");
        }
        if(s.equals("5"))
        {
            s1.setText("Structural Analysis-II");
            s2.setText("Structural Engineering Design-I");
            s3.setText("Geotech Engineering-I");
            s4.setText("Transportation Engineering-II");
            s5.setText("Numerical Methods & Computer Programming");
            s6.setText("Engineering Hydrology");
        }
        if(s.equals("6"))
        {
            s1.setText("Structural Engineering Design-II");
            s2.setText("Geotech Engineering-II");
            s3.setText("Environmental Engineering-I");
            s4.setText("Concrete Technology");
            s5.setText("Construction Planning");
            s6.setText("Composite Materials");
        }
        if(s.equals("7"))
        {
            s1.setText("Structural Engineering Design-III");
            s2.setText("Water Resources Engineering-I");
            s3.setText("Environmental Engineering-I");
            s4.setText("Quantity Surveying & Cost Evaluation");
            s5.setText("Safety in Construction");
        }
        if(s.equals("8"))
        {
            s1.setText("Structural Engineering Design-IV");
            s2.setText("Water Resources Engineering-II");
            s3.setText("Structural Analysis-III");
            s4.setText("Industrial Waste Treatment");
            s5.setText("Disaster Management");
        }
    }
    if(b.equals("Mechanical Engineering"))
    {
        if(s.equals("1"))
        {
            s1.setText("Applied Physics");
            s2.setText("Fundamentals Of Mechanical Engineering");
            s3.setText("Mathematics-I");
            s4.setText("Environment & Ecology");
            s5.setText("Basic Civil Engineering");
        }
        if(s.equals("2"))
        {
            s1.setText("Applied Chemistry");
            s2.setText("Elements Of Electrical Engineering");
            s3.setText("Mathematics-III");
            s4.setText("Communication Skills");
            s5.setText("Engineering Graphics");
        }
        if(s.equals("3"))
        {
            s1.setText("Mathematics-III");
            s2.setText("Machine Drawing");
            s3.setText("Material Science & Metallurgy");
            s4.setText("Mechanics Of Solids-I");
            s5.setText("Engineering Thermodynamics");
            s6.setText("Mechanical Instruments & Metrology");
        }
        if(s.equals("4"))
        {
            s1.setText("Fluid Mechanics");
            s2.setText("Mechanics Of Solids-II");
            s3.setText("Applied Thermodynamics");
            s4.setText("Kinematics Of Machines");
            s5.setText("Numerical Analysis & Computer Programming(c/C++)");
            s6.setText("Manufacturing Science-I");
        }
        if(s.equals("5"))
        {
            s1.setText("Machine Design-I");
            s2.setText("Turbo Machinery");
            s3.setText("Dynamics Of Machines");
            s4.setText("Fluid Machinery");
            s5.setText("Manufacturing Science-II");
            s6.setText("Operations Research");
        }
        if(s.equals("6"))
        {
            s1.setText("Machine Design-II");
            s2.setText("Energy Systems");
            s3.setText("Internal Combustion Engines");
            s4.setText("Heat & Mass Transfer");
            s5.setText("Production Management");
            s6.setText("Composite Materials");
        }
        if(s.equals("7"))
        {
            s1.setText("Automobile Engineering");
            s2.setText("Refrigeration & Air-Conditioning");
            s3.setText("Computer Aided Design & Manufacturing");
            s4.setText("Machine Tool Technology");
            s5.setText("Applied Elasticity & Plasticity");
        }
        if(s.equals("8"))
        {
            s1.setText("Robotics");
            s2.setText("Finite Element Methods");
            s3.setText("Industrial Engineering & Management");
            s4.setText("Mechatronics");
            s5.setText("Safety Engineering");
        }
    }
    if(b.equals("Electrical Engineering"))
    {
        if(s.equals("1"))
        {
            s1.setText("Applied Chemistry");
            s2.setText("Elements  Of Electrical Engineering");
            s3.setText("Mathematics-I");
            s4.setText("Communication Skills");
            s5.setText("Engineering Graphics");
        }
        if(s.equals("2"))
        {
            s1.setText("Applied Physics");
            s2.setText("Fundamentals Of Mechanical Engineering");
            s3.setText("Mathematics-II");
            s4.setText("Environment & Ecology");
            s5.setText("Basic Civil Engineering");
        }
        if(s.equals("3"))
        {
            s1.setText("Mathematics-III");
            s2.setText("Electrical Machines");
            s3.setText("Basic Electronics");
            s4.setText("Electric Circuits");
            s5.setText("Electrical Engineering & Material");
            s6.setText("Electrical Power Generation");
        }
        if(s.equals("4"))
        {
            s1.setText("Analog Electronics");
            s2.setText("Electro Magnetic Theory");
            s3.setText("Network Analysis & Synthesis");
            s4.setText("Digital Electronics & Logic Design");
            s5.setText("Electrical Power Systems");
            s6.setText("Electrical Measurements & Measuring Instruments");
        }
        if(s.equals("5"))
        {
            s1.setText("Electrical Machines-II");
            s2.setText("Microprocessor & Interfacing");
            s3.setText("Applied Numerical Analysis");
            s4.setText("Integrated Circuits");
            s5.setText("Control System Engineering");
            s6.setText("Communication Theory");
        }
        if(s.equals("6"))
        {
            s1.setText("Power System Analysis");
            s2.setText("Electrical Machines-III");
            s3.setText("Power Electronics");
            s4.setText("Instrumntation Techniques");
            s5.setText("Priciples Of Digital Signal Processing");
            s6.setText("Fibre Optics");
        }
        if(s.equals("7"))
        {
            s1.setText("Switchgear & Protection");
            s2.setText("Modern Control System");
            s3.setText("Electrical Devices");
            s4.setText("Energy Auditing & Management");
            s5.setText("Microcontroller & Embedded Systems");
        }
        if(s.equals("8"))
        {
            s1.setText("High Voltage Engineering");
            s2.setText("Management Concepts & Techniques");
            s3.setText("Installation Maintenance & Testing Of Electrical Equipments");
            s4.setText("Robotics & Automation");
            s5.setText("Electrical Estimation & Costing");
        }
    }
    if(b.equals("Electrical & Electronics Engineering"))
    {
        if(s.equals("1"))
        {
            s1.setText("Applied Chemistry");
            s2.setText("Elements  Of Electrical Engineering");
            s3.setText("Mathematics-I");
            s4.setText("Communication Skills");
            s5.setText("Engineering Graphics");
        }
        if(s.equals("2"))
        {
            s1.setText("Applied Physics");
            s2.setText("Fundamentals Of Mechanical Engineering");
            s3.setText("Mathematics-II");
            s4.setText("Environment & Ecology");
            s5.setText("Basic Civil Engineering");
        }
        if(s.equals("3"))
        {
            s1.setText("Mathematics-III");
            s2.setText("Numerical Analysis");
            s3.setText("Basic Electronics");
            s4.setText("Electric Circuits");
            s5.setText("Electrical Power Generation");
            s6.setText("Electrical Machines-I");
        }
        if(s.equals("4"))
        {
            s1.setText("Network Analysis & Synthesis");
            s2.setText("Electromagnetic Theory");
            s3.setText("Electrical Measurements & Measuring Instruments");
            s4.setText("Electrical Power Systems");
            s5.setText("Analog Electronics");
            s6.setText("Digital Electronics & Logic Design");
        }
        if(s.equals("5"))
        {
            s1.setText("Microprocessor & Peripherals");
            s2.setText("Integrated Circuits & Applications");
            s3.setText("Linear Control Systems");
            s4.setText("Signals & Systems");
            s5.setText("Electrical Machines-II");
            s6.setText("Communication Systems");
        }
        if(s.equals("6"))
        {
            s1.setText("Electrical Power System-II");
            s2.setText("Modern Instrumentaion Techniques");
            s3.setText("Advanced Microprocessor & Peripherals");
            s4.setText("Power Electronic Devices & Circuits");
            s5.setText("Digital Signal Processing");
            s6.setText("Medical Electronics");
        }
        if(s.equals("7"))
        {
            s1.setText("Switchgear & Protection");
            s2.setText("Soft Computing & Its Applications");
            s3.setText("Electrical Devices");
            s4.setText("Microcontrollers & Applications");
            s5.setText("Illumination Engineering");
        }
        if(s.equals("8"))
        {
            s1.setText("High Voltage Engineering");
            s2.setText("Management Concepts & Techniques");
            s3.setText("Computer Aided Power System");
            s4.setText("VLSI Design");
            s5.setText("Non-Conventional Energy Sources");
        }
    }
    if(b.equals("Electronics & Telecommunication Engineering"))
    {
        if(s.equals("1"))
        {
            s1.setText("Applied Chemistry");
            s2.setText("Elements  Of Electrical Engineering");
            s3.setText("Mathematics-I");
            s4.setText("Communication Skills");
            s5.setText("Engineering Graphics");
        }
        if(s.equals("2"))
        {
            s1.setText("Applied Physics");
            s2.setText("Fundamentals Of Mechanical Engineering");
            s3.setText("Mathematics-II");
            s4.setText("Environment & Ecology");
            s5.setText("Basic Civil Engineering");
        }
        if(s.equals("4"))
        {
            s1.setText("Numerical Analysis using C");
            s2.setText("Analog Comunication");
            s3.setText("Analog Electronics");
            s4.setText("Microprocessor & Interfaces");
            s5.setText("Signals & Systems");
            s6.setText("Electromagnetic Fields & Transmission Lines");
        }
        if(s.equals("5"))
        {
            s1.setText("Linear Integrated Circuits & Applications");
            s2.setText("Data Structures & Programming with C++");
            s3.setText("Antennas & Wave Propagation");
            s4.setText("Digital Communication");
            s5.setText("Advanced Micrprocessor & Interfacing");
            s6.setText("Automatic Control System");
        }
        if(s.equals("6"))
        {
            s1.setText("Digital Signal Processing");
            s2.setText("Electronic Circuit & Design");
            s3.setText("Microcontroller & Embedded System");
            s4.setText("VLSI Design");
            s5.setText("Information Theory & Coding");
            s6.setText("Biomedical Electronics");
        }
        if(s.equals("7"))
        {
            s1.setText("Microwave Communication & Engineering");
            s2.setText("Computer Networks");
            s3.setText("Wireless Communications");
            s4.setText("Management Concepts & Techniques");
            s5.setText("Radar & Navigational Aids");
        }
        if(s.equals("8"))
        {
            s1.setText("Advanced Communication Systems");
            s2.setText("Consumer Electronics");
            s3.setText("Power Electronics");
            s4.setText("Cryptography & Secure Communication");
            s5.setText("Biometrics");
        }
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void s1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s1FocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_s1FocusGained

    private void s1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s1FocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_s1FocusLost

    private void s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s1ActionPerformed

    private void s2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s2FocusGained
        // TODO add your handling code here:
       
    }//GEN-LAST:event_s2FocusGained

    private void s2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s2FocusLost
        // TODO add your handling code here:
      
    }//GEN-LAST:event_s2FocusLost

    private void s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s2ActionPerformed

    private void s3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_s3FocusGained

    private void s3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s3FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_s3FocusLost

    private void s3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s3ActionPerformed

    private void s4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s4FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_s4FocusGained

    private void s4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s4FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_s4FocusLost

    private void s4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s4ActionPerformed

    private void s5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s5FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_s5FocusGained

    private void s5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s5FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_s5FocusLost

    private void s5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s5ActionPerformed

    private void s6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s6FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_s6FocusGained

    private void s6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s6FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_s6FocusLost

    private void s6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s6ActionPerformed

    private void m1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_m1FocusGained

    private void m1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_m1FocusLost

    private void m1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m1ActionPerformed

    private void m2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_m2FocusGained

    private void m2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_m2FocusLost

    private void m2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m2ActionPerformed

    private void m3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_m3FocusGained

    private void m3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m3FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_m3FocusLost

    private void m3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m3ActionPerformed

    private void m4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m4FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_m4FocusGained

    private void m4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m4FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_m4FocusLost

    private void m4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m4ActionPerformed

    private void m5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m5FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_m5FocusGained

    private void m5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m5FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_m5FocusLost

    private void m5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m5ActionPerformed

    private void m6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m6FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_m6FocusGained

    private void m6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m6FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_m6FocusLost

    private void m6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try
        {
            String r=t1.getText();   
            String ct=co1.getSelectedItem().toString();
            String s1name=s1.getText();
            String s2name=s2.getText();
            String s3name=s3.getText();
            String s4name=s4.getText();
            String s5name=s5.getText();
            String s6name=s6.getText();
            String m1marks=m1.getText();
            String m2marks=m2.getText();
            String m3marks=m3.getText();
            String m4marks=m4.getText();
            String m5marks=m5.getText();
            String m6marks=m6.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/ctproject","root","");
            String q="insert into ctdetail values('"+r+"','"+ct+"','"+s1name+"','"+s2name+"','"+s3name+"','"+s4name+"','"+s5name+"','"+s6name+"','"+m1marks+"','"+m2marks+"','"+m3marks+"','"+m4marks+"','"+m5marks+"','"+m6marks+"')";
           Statement stmt=con.createStatement();
           int rs=stmt.executeUpdate(q);
           if(rs!=0)
           {
               JOptionPane.showMessageDialog(this, "Save Successfully !");
           }   
           con.close();
        }
        catch(Exception ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AddStudent add=new AddStudent();
        add.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> co1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField m1;
    private javax.swing.JTextField m2;
    private javax.swing.JTextField m3;
    private javax.swing.JTextField m4;
    private javax.swing.JTextField m5;
    private javax.swing.JTextField m6;
    private javax.swing.JTextField s1;
    private javax.swing.JTextField s2;
    private javax.swing.JTextField s3;
    private javax.swing.JTextField s4;
    private javax.swing.JTextField s5;
    private javax.swing.JTextField s6;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JComboBox<String> t3;
    private javax.swing.JComboBox<String> t4;
    // End of variables declaration//GEN-END:variables
}
