/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ctmarks;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Ashish
 */
public class EditCT extends javax.swing.JFrame {

    /**
     * Creates new form AddCT
     */
    public EditCT() {
        initComponents();
        jLabel6.setFocusable(true);
        s6.setVisible(false);
        m6.setVisible(false);
        jSeparator8.setVisible(false);
        jSeparator14.setVisible(false);
        //this.setSize(800,500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textBox = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        co1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        s1 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        s2 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        s3 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        s4 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        s5 = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        s6 = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        m1 = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        m2 = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        m3 = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        m4 = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        m5 = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        m6 = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(43, 42, 76));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textBox.setBackground(new java.awt.Color(43, 42, 76));
        textBox.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        textBox.setForeground(new java.awt.Color(255, 255, 255));
        textBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textBox.setText("Roll No.");
        textBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        textBox.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textBoxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textBoxFocusLost(evt);
            }
        });
        textBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBoxActionPerformed(evt);
            }
        });
        jPanel1.add(textBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 210, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 210, 10));

        jButton1.setBackground(new java.awt.Color(43, 42, 76));
        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Go");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 60, 40));

        co1.setBackground(new java.awt.Color(43, 42, 76));
        co1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        co1.setForeground(new java.awt.Color(255, 255, 255));
        co1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "           --CT--", "1", "2" }));
        jPanel1.add(co1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 170, 30));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 3, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Marks");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 90, 30));

        s1.setBackground(new java.awt.Color(43, 42, 76));
        s1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        s1.setForeground(new java.awt.Color(255, 255, 255));
        s1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        s1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                s1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                s1FocusLost(evt);
            }
        });
        s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1ActionPerformed(evt);
            }
        });
        jPanel1.add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 280, 30));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 280, 20));

        s2.setBackground(new java.awt.Color(43, 42, 76));
        s2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        s2.setForeground(new java.awt.Color(255, 255, 255));
        s2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        s2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                s2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                s2FocusLost(evt);
            }
        });
        s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s2ActionPerformed(evt);
            }
        });
        jPanel1.add(s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 280, 30));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 280, 20));

        s3.setBackground(new java.awt.Color(43, 42, 76));
        s3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        s3.setForeground(new java.awt.Color(255, 255, 255));
        s3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        s3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                s3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                s3FocusLost(evt);
            }
        });
        s3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s3ActionPerformed(evt);
            }
        });
        jPanel1.add(s3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 280, 30));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 280, 20));

        s4.setBackground(new java.awt.Color(43, 42, 76));
        s4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        s4.setForeground(new java.awt.Color(255, 255, 255));
        s4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        s4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                s4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                s4FocusLost(evt);
            }
        });
        s4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s4ActionPerformed(evt);
            }
        });
        jPanel1.add(s4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 280, 30));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 280, 20));

        s5.setBackground(new java.awt.Color(43, 42, 76));
        s5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        s5.setForeground(new java.awt.Color(255, 255, 255));
        s5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        s5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                s5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                s5FocusLost(evt);
            }
        });
        s5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s5ActionPerformed(evt);
            }
        });
        jPanel1.add(s5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 280, 30));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 280, 20));

        s6.setBackground(new java.awt.Color(43, 42, 76));
        s6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        s6.setForeground(new java.awt.Color(255, 255, 255));
        s6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        s6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                s6FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                s6FocusLost(evt);
            }
        });
        s6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s6ActionPerformed(evt);
            }
        });
        jPanel1.add(s6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 280, 30));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 280, 20));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 3, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Subjects");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 90, 30));

        m1.setBackground(new java.awt.Color(43, 42, 76));
        m1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        m1.setForeground(new java.awt.Color(255, 255, 255));
        m1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        m1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                m1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                m1FocusLost(evt);
            }
        });
        m1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m1ActionPerformed(evt);
            }
        });
        jPanel1.add(m1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 170, 30));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 170, 20));

        m2.setBackground(new java.awt.Color(43, 42, 76));
        m2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        m2.setForeground(new java.awt.Color(255, 255, 255));
        m2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        m2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                m2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                m2FocusLost(evt);
            }
        });
        m2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m2ActionPerformed(evt);
            }
        });
        jPanel1.add(m2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 170, 30));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 170, 20));

        m3.setBackground(new java.awt.Color(43, 42, 76));
        m3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        m3.setForeground(new java.awt.Color(255, 255, 255));
        m3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        m3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                m3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                m3FocusLost(evt);
            }
        });
        m3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m3ActionPerformed(evt);
            }
        });
        jPanel1.add(m3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 170, 30));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 170, 20));

        m4.setBackground(new java.awt.Color(43, 42, 76));
        m4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        m4.setForeground(new java.awt.Color(255, 255, 255));
        m4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        m4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                m4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                m4FocusLost(evt);
            }
        });
        m4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m4ActionPerformed(evt);
            }
        });
        jPanel1.add(m4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 170, 30));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 170, 20));

        m5.setBackground(new java.awt.Color(43, 42, 76));
        m5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        m5.setForeground(new java.awt.Color(255, 255, 255));
        m5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        m5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                m5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                m5FocusLost(evt);
            }
        });
        m5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m5ActionPerformed(evt);
            }
        });
        jPanel1.add(m5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 170, 30));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 170, 20));

        m6.setBackground(new java.awt.Color(43, 42, 76));
        m6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        m6.setForeground(new java.awt.Color(255, 255, 255));
        m6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        m6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                m6FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                m6FocusLost(evt);
            }
        });
        m6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m6ActionPerformed(evt);
            }
        });
        jPanel1.add(m6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 170, 30));
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, 170, 20));

        jButton4.setBackground(new java.awt.Color(43, 42, 76));
        jButton4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, 110, 40));

        jButton5.setBackground(new java.awt.Color(43, 42, 76));
        jButton5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, 110, 40));

        jLabel4.setFont(new java.awt.Font("aliens and cows", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Marks");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 110, 40));

        jLabel3.setFont(new java.awt.Font("RolinaBold", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Via");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 40, 40));

        jLabel5.setFont(new java.awt.Font("aliens and cows", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SMS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 70, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ashish\\Downloads\\learning3.png")); // NOI18N
        jLabel6.setText("jLabel2");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 79, 72));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textBoxFocusGained
        // TODO add your handling code here:
        if(textBox.getText().equals("Roll No."))
        {
            textBox.setText("");
        }
    }//GEN-LAST:event_textBoxFocusGained

    private void textBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textBoxFocusLost
        // TODO add your handling code here:
        if(textBox.getText().equals(""))
        {
            textBox.setText("Roll No.");
        }
    }//GEN-LAST:event_textBoxFocusLost

    private void textBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
            String r=textBox.getText();   
            String ct=co1.getSelectedItem().toString();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/ctproject","root","");
            String q="select * from ctdetail where roll_no='"+r+"' and ct='"+ct+"'";
           Statement stmt=con.createStatement();
           ResultSet rs=stmt.executeQuery(q);
           while(rs.next())
           {
               s1.setText(rs.getString("s1name"));
               s2.setText(rs.getString("s2name"));
               s3.setText(rs.getString("s3name"));
               s4.setText(rs.getString("s4name"));
               s5.setText(rs.getString("s5name"));
               s6.setText(rs.getString("s6name"));
               m1.setText(rs.getString("s1marks"));
               m2.setText(rs.getString("s2marks"));
               m3.setText(rs.getString("s3marks"));
               m4.setText(rs.getString("s4marks"));
               m5.setText(rs.getString("s5marks"));
               m6.setText(rs.getString("s6marks"));
           }   
           con.close();
        }
        catch(Exception ex)
        {
            System.out.println(ex);
        }
        if(!s6.equals("") && !m6.equals("")) {
            s6.setVisible(true);
            jSeparator8.setVisible(true);
            m6.setVisible(true);
            jSeparator14.setVisible(true);
            pack();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void s1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s1FocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_s1FocusGained

    private void s1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s1FocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_s1FocusLost

    private void s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s1ActionPerformed

    private void s2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s2FocusGained
        // TODO add your handling code here:
       
    }//GEN-LAST:event_s2FocusGained

    private void s2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s2FocusLost
        // TODO add your handling code here:
      
    }//GEN-LAST:event_s2FocusLost

    private void s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s2ActionPerformed

    private void s3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_s3FocusGained

    private void s3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s3FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_s3FocusLost

    private void s3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s3ActionPerformed

    private void s4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s4FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_s4FocusGained

    private void s4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s4FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_s4FocusLost

    private void s4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s4ActionPerformed

    private void s5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s5FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_s5FocusGained

    private void s5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s5FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_s5FocusLost

    private void s5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s5ActionPerformed

    private void s6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s6FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_s6FocusGained

    private void s6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s6FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_s6FocusLost

    private void s6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s6ActionPerformed

    private void m1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_m1FocusGained

    private void m1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_m1FocusLost

    private void m1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m1ActionPerformed

    private void m2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_m2FocusGained

    private void m2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_m2FocusLost

    private void m2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m2ActionPerformed

    private void m3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_m3FocusGained

    private void m3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m3FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_m3FocusLost

    private void m3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m3ActionPerformed

    private void m4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m4FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_m4FocusGained

    private void m4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m4FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_m4FocusLost

    private void m4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m4ActionPerformed

    private void m5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m5FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_m5FocusGained

    private void m5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m5FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_m5FocusLost

    private void m5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m5ActionPerformed

    private void m6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m6FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_m6FocusGained

    private void m6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m6FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_m6FocusLost

    private void m6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try
        {
            String r=textBox.getText();   
            String ct=co1.getSelectedItem().toString();
            String s1name=s1.getText();
            String s2name=s2.getText();
            String s3name=s3.getText();
            String s4name=s4.getText();
            String s5name=s5.getText();
            String s6name=s6.getText();
            String m1marks=m1.getText();
            String m2marks=m2.getText();
            String m3marks=m3.getText();
            String m4marks=m4.getText();
            String m5marks=m5.getText();
            String m6marks=m6.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/ctproject","root","");
            String q="update ctdetail set s1name='"+s1name+"',s2name='"+s2name+"',s3name='"+s3name+"',s4name='"+s4name+"',s5name='"+s5name+"',s6name='"+s6name+"',s1marks='"+m1marks+"',s2marks='"+m2marks+"',s3marks='"+m3marks+"',s4marks='"+m4marks+"',s5marks='"+m5marks+"',s6marks='"+m6marks+"'";
           Statement stmt=con.createStatement();
           int rs=stmt.executeUpdate(q);
           if(rs!=0)
           {
               JOptionPane.showMessageDialog(this, "Saved Successfully !");
           }   
           con.close();
        }
        catch(Exception ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AddStudent add=new AddStudent();
        add.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditCT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> co1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField m1;
    private javax.swing.JTextField m2;
    private javax.swing.JTextField m3;
    private javax.swing.JTextField m4;
    private javax.swing.JTextField m5;
    private javax.swing.JTextField m6;
    private javax.swing.JTextField s1;
    private javax.swing.JTextField s2;
    private javax.swing.JTextField s3;
    private javax.swing.JTextField s4;
    private javax.swing.JTextField s5;
    private javax.swing.JTextField s6;
    private javax.swing.JTextField textBox;
    // End of variables declaration//GEN-END:variables
}
