/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ctmarks;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.URL;
import java.net.URLConnection;
import java.net.URLEncoder;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Ashish
 */
public class SMSRoll extends javax.swing.JFrame {

    /**
     * Creates new form AddCT
     */
    public static String retval="";
    
    public static String SMSSender(String user,String password,String msisdn,String msg,String sid,String fl)    
    {
        
        String rsp="";
        
        try {
            // Construct The Post Data
            String data = URLEncoder.encode("user", "UTF-8") + "=" + URLEncoder.encode(user, "UTF-8");
            data += "&" + URLEncoder.encode("password", "UTF-8") + "=" + URLEncoder.encode(password, "UTF-8");
            data += "&" + URLEncoder.encode("msisdn", "UTF-8") + "=" + URLEncoder.encode(msisdn, "UTF-8");
            data += "&" + URLEncoder.encode("msg", "UTF-8") + "=" + URLEncoder.encode(msg, "UTF-8");
            data += "&" + URLEncoder.encode("sid", "UTF-8") + "=" + URLEncoder.encode(sid, "UTF-8");
            data += "&" + URLEncoder.encode("fl", "UTF-8") + "=" + URLEncoder.encode(fl, "UTF-8");
            data += "&" + URLEncoder.encode("gwid", "UTF-8") + "=" + URLEncoder.encode("2", "UTF-8");
            
            //Push the HTTP Request
            URL url = new URL("http://smslane.com/vendorsms/pushsms.aspx");
            URLConnection conn = url.openConnection();
            conn.setDoOutput(true);
        
            OutputStreamWriter wr = new OutputStreamWriter(conn.getOutputStream());
            wr.write(data);
            wr.flush();
           
            //Read The Response
            BufferedReader rd = new BufferedReader(new InputStreamReader(conn.getInputStream()));
            String line;
            while ((line = rd.readLine()) != null) {
                // Process line...
                retval += line;
            }
            wr.close();
            rd.close();
            
            System.out.println(retval);
            rsp = retval;
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        return  rsp;
    }
    public SMSRoll() {
        initComponents();
        jLabel3.setFocusable(true);
        s6.setVisible(false);
        m6.setVisible(false);
        jSeparator8.setVisible(false);
        jSeparator14.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        s1 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        s2 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        s3 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        s4 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        s5 = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        s6 = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        m1 = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        m2 = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        m3 = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        m4 = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        m5 = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        m6 = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        t2 = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        t3 = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 520));

        jPanel1.setBackground(new java.awt.Color(43, 42, 76));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 520));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(43, 42, 76));
        jTextField1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Roll No.");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 210, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 210, 10));

        jButton1.setBackground(new java.awt.Color(43, 42, 76));
        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Go");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 60, 40));

        t1.setBackground(new java.awt.Color(43, 42, 76));
        t1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        t1.setForeground(new java.awt.Color(255, 255, 255));
        t1.setText("Name");
        t1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        t1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t1FocusLost(evt);
            }
        });
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        jPanel1.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 330, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 330, 20));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Marks");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 90, 30));

        s1.setBackground(new java.awt.Color(43, 42, 76));
        s1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        s1.setForeground(new java.awt.Color(255, 255, 255));
        s1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        s1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                s1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                s1FocusLost(evt);
            }
        });
        s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1ActionPerformed(evt);
            }
        });
        jPanel1.add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 270, 30));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 270, 20));

        s2.setBackground(new java.awt.Color(43, 42, 76));
        s2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        s2.setForeground(new java.awt.Color(255, 255, 255));
        s2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        s2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                s2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                s2FocusLost(evt);
            }
        });
        s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s2ActionPerformed(evt);
            }
        });
        jPanel1.add(s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 270, 30));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 270, 20));

        s3.setBackground(new java.awt.Color(43, 42, 76));
        s3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        s3.setForeground(new java.awt.Color(255, 255, 255));
        s3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        s3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                s3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                s3FocusLost(evt);
            }
        });
        s3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s3ActionPerformed(evt);
            }
        });
        jPanel1.add(s3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 270, 30));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 270, 20));

        s4.setBackground(new java.awt.Color(43, 42, 76));
        s4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        s4.setForeground(new java.awt.Color(255, 255, 255));
        s4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        s4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                s4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                s4FocusLost(evt);
            }
        });
        s4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s4ActionPerformed(evt);
            }
        });
        jPanel1.add(s4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 270, 30));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 270, 20));

        s5.setBackground(new java.awt.Color(43, 42, 76));
        s5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        s5.setForeground(new java.awt.Color(255, 255, 255));
        s5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        s5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                s5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                s5FocusLost(evt);
            }
        });
        s5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s5ActionPerformed(evt);
            }
        });
        jPanel1.add(s5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 270, 30));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 270, 20));

        s6.setBackground(new java.awt.Color(43, 42, 76));
        s6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        s6.setForeground(new java.awt.Color(255, 255, 255));
        s6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        s6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                s6FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                s6FocusLost(evt);
            }
        });
        s6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s6ActionPerformed(evt);
            }
        });
        jPanel1.add(s6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 270, 30));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 270, 20));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Subjects");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 90, 30));

        m1.setBackground(new java.awt.Color(43, 42, 76));
        m1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        m1.setForeground(new java.awt.Color(255, 255, 255));
        m1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        m1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                m1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                m1FocusLost(evt);
            }
        });
        m1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m1ActionPerformed(evt);
            }
        });
        jPanel1.add(m1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 170, 30));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 170, 20));

        m2.setBackground(new java.awt.Color(43, 42, 76));
        m2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        m2.setForeground(new java.awt.Color(255, 255, 255));
        m2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        m2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                m2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                m2FocusLost(evt);
            }
        });
        m2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m2ActionPerformed(evt);
            }
        });
        jPanel1.add(m2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 170, 30));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 170, 20));

        m3.setBackground(new java.awt.Color(43, 42, 76));
        m3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        m3.setForeground(new java.awt.Color(255, 255, 255));
        m3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        m3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                m3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                m3FocusLost(evt);
            }
        });
        m3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m3ActionPerformed(evt);
            }
        });
        jPanel1.add(m3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 170, 30));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 170, 20));

        m4.setBackground(new java.awt.Color(43, 42, 76));
        m4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        m4.setForeground(new java.awt.Color(255, 255, 255));
        m4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        m4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                m4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                m4FocusLost(evt);
            }
        });
        m4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m4ActionPerformed(evt);
            }
        });
        jPanel1.add(m4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 170, 30));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 170, 20));

        m5.setBackground(new java.awt.Color(43, 42, 76));
        m5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        m5.setForeground(new java.awt.Color(255, 255, 255));
        m5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        m5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                m5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                m5FocusLost(evt);
            }
        });
        m5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m5ActionPerformed(evt);
            }
        });
        jPanel1.add(m5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 170, 30));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 170, 20));

        m6.setBackground(new java.awt.Color(43, 42, 76));
        m6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        m6.setForeground(new java.awt.Color(255, 255, 255));
        m6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        m6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                m6FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                m6FocusLost(evt);
            }
        });
        m6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m6ActionPerformed(evt);
            }
        });
        jPanel1.add(m6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 170, 30));
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, 170, 20));

        jButton4.setBackground(new java.awt.Color(43, 42, 76));
        jButton4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Send");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, 110, 40));

        jComboBox2.setBackground(new java.awt.Color(43, 42, 76));
        jComboBox2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "           --CT--", "1", "2" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 170, 30));

        t2.setBackground(new java.awt.Color(43, 42, 76));
        t2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        t2.setForeground(new java.awt.Color(255, 255, 255));
        t2.setText("Parent's Name");
        t2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        t2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t2FocusLost(evt);
            }
        });
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        jPanel1.add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 330, 30));
        jPanel1.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 330, 20));

        t3.setBackground(new java.awt.Color(43, 42, 76));
        t3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        t3.setForeground(new java.awt.Color(255, 255, 255));
        t3.setText("Parent's Mobile");
        t3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 42, 76)));
        t3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t3FocusLost(evt);
            }
        });
        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        jPanel1.add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 170, 30));
        jPanel1.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 170, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ashish\\Downloads\\learning3.png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        // TODO add your handling code here:
        if(jTextField1.getText().equals("Roll No."))
        {
            jTextField1.setText("");
        }
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        // TODO add your handling code here:
        if(jTextField1.getText().equals(""))
        {
            jTextField1.setText("Roll No.");
        }
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void t1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t1FocusGained
        // TODO add your handling code here:
        if(t1.getText().equals("Name"))
        {
            t1.setText("");
        }
    }//GEN-LAST:event_t1FocusGained

    private void t1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t1FocusLost
        // TODO add your handling code here:
        if(t1.getText().equals(""))
        {
            t1.setText("Name");
        }
    }//GEN-LAST:event_t1FocusLost

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
            String r=jTextField1.getText();   
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/ctproject","root","");
            String q="select * from student where roll_no='"+r+"'";
           Statement stmt=con.createStatement();
           ResultSet rs=stmt.executeQuery(q);
           while(rs.next())
           {
               t1.setText(rs.getString("name"));
               t2.setText(rs.getString("pname"));
               t3.setText(rs.getString("pmobile"));
           }   
           con.close();
        }
        catch(Exception ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void s1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s1FocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_s1FocusGained

    private void s1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s1FocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_s1FocusLost

    private void s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s1ActionPerformed

    private void s2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s2FocusGained
        // TODO add your handling code here:
       
    }//GEN-LAST:event_s2FocusGained

    private void s2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s2FocusLost
        // TODO add your handling code here:
      
    }//GEN-LAST:event_s2FocusLost

    private void s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s2ActionPerformed

    private void s3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_s3FocusGained

    private void s3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s3FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_s3FocusLost

    private void s3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s3ActionPerformed

    private void s4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s4FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_s4FocusGained

    private void s4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s4FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_s4FocusLost

    private void s4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s4ActionPerformed

    private void s5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s5FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_s5FocusGained

    private void s5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s5FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_s5FocusLost

    private void s5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s5ActionPerformed

    private void s6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s6FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_s6FocusGained

    private void s6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_s6FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_s6FocusLost

    private void s6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s6ActionPerformed

    private void m1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_m1FocusGained

    private void m1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_m1FocusLost

    private void m1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m1ActionPerformed

    private void m2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_m2FocusGained

    private void m2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_m2FocusLost

    private void m2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m2ActionPerformed

    private void m3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_m3FocusGained

    private void m3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m3FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_m3FocusLost

    private void m3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m3ActionPerformed

    private void m4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m4FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_m4FocusGained

    private void m4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m4FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_m4FocusLost

    private void m4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m4ActionPerformed

    private void m5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m5FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_m5FocusGained

    private void m5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m5FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_m5FocusLost

    private void m5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m5ActionPerformed

    private void m6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m6FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_m6FocusGained

    private void m6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m6FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_m6FocusLost

    private void m6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String S1=s1.getText();
        String S2=s2.getText();
        String S3=s3.getText();
        String S4=s4.getText();
        String S5=s5.getText();
        String S6=s6.getText();
        String M1=m1.getText();
        String M2=m2.getText();
        String M3=m3.getText();
        String M4=m4.getText();
        String M5=m5.getText();
        String M6=m6.getText();
        String Name=t1.getText();        
        String mobile=t3.getText();
        String text=Name+S1+M1+S2+M2+S3+M3+S4+M4+S5+M5+S6+M6;
        String response = SMSSender("vemujyotirao@yahoo.co.in", "vemu1989","91"+mobile,""+text, "TOSCAL", "0"); 
        System.out.println(response);
        JOptionPane.showMessageDialog(this, "Sent Successfully !");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void t2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_t2FocusGained

    private void t2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_t2FocusLost

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void t3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_t3FocusGained

    private void t3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t3FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_t3FocusLost

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        try
        {
            String CT=(String) jComboBox2.getSelectedItem();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/ctproject","root","");
            String q="select * from ctdetail where ct='"+CT+"'";
           Statement stmt=con.createStatement();
           ResultSet rs=stmt.executeQuery(q);
           while(rs.next())
           {
               s1.setText(rs.getString("s1name"));
               s2.setText(rs.getString("s2name"));
               s3.setText(rs.getString("s3name"));
               s4.setText(rs.getString("s4name"));
               s5.setText(rs.getString("s5name"));
               s6.setText(rs.getString("s6name"));
               m1.setText(rs.getString("s1marks"));
               m2.setText(rs.getString("s2marks"));
               m3.setText(rs.getString("s3marks"));
               m4.setText(rs.getString("s4marks"));
               m5.setText(rs.getString("s5marks"));
               m6.setText(rs.getString("s6marks"));
           }   
           con.close();
        }
        catch(Exception ex)
        {
            System.out.println(ex);
        }
        if(!s6.equals("") && !m6.equals("")) {
            s6.setVisible(true);
            jSeparator8.setVisible(true);
            m6.setVisible(true);
            jSeparator14.setVisible(true);
            pack();
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SMSRoll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SMSRoll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SMSRoll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SMSRoll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SMSRoll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField m1;
    private javax.swing.JTextField m2;
    private javax.swing.JTextField m3;
    private javax.swing.JTextField m4;
    private javax.swing.JTextField m5;
    private javax.swing.JTextField m6;
    private javax.swing.JTextField s1;
    private javax.swing.JTextField s2;
    private javax.swing.JTextField s3;
    private javax.swing.JTextField s4;
    private javax.swing.JTextField s5;
    private javax.swing.JTextField s6;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    // End of variables declaration//GEN-END:variables
}
